name: IntegratedMGTBenchFramework
channels:
  - defaults
dependencies:
  - python=3.10
  - pip=23.2.1
  - pip:
    - transformers==4.33.1
    - matplotlib==3.7.3
    - keras==2.13.1
    - numpy==1.24.3
    - torch==2.0.1
    - scikit-learn==1.3.0
    - tensorflow==2.13.0
    - tqdm==4.66.1
    - pandas==2.0.3
    - datasets==2.14.5
    - seaborn==0.12.2