name: IMGTB
channels:
  - defaults
dependencies:
  - python>2.10
  - pip
  - pip:
    - transformers
    - matplotlib
    - keras
    - numpy
    - torch
    - scikit-learn
    - tensorflow
    - tqdm
    - pandas
    - datasets
    - seaborn
    - xlrd
    - pyarrow
    - lxml
    - openpyxl
    - evaluate
    - accelerate
    - sentencepiece
    - fasttext==0.9.1
    - fasttext-langdetect
    - peft
    - bitsandbytes

