name: IMGTB
channels:
  - defaults
dependencies:
  - python=3.10
  - pip=23.2.1
  - pip:
    - transformers==4.33.1
    - matplotlib==3.7.3
    - keras==2.14.0
    - numpy==1.26.0
    - torch==2.0.1
    - scikit-learn==1.3.0
    - tensorflow==2.14.0
    - tqdm==4.66.1
    - pandas==2.0.3
    - datasets==2.14.5
    - seaborn==0.12.2
    - xlrd==2.0.1
    - pyarrow==13.0.0
    - lxml==4.9.3
    - openpyxl==3.0.10
    - evaluate==0.4.1
    - accelerate==0.25.0
    - sentencepiece==0.1.99
    - fasttext-langdetect==1.0.5
    - peft==0.9.0
    - bitsandbytes==0.42.0

