---
# Global data passed only to the "manager" component (benchmark.py in this case).
# They will not be passed (directly) to any library or detection method.
global: 
  interactive: false
  name: miracle_method_eval

# Global parameters will be used with all datasets in the list, 
# if not specified differently in the individual dataset parameters.
# (parameters in data/list have precedence)
data:
  global:
    filetype: auto
  list:
  - filepath: xzuyn/futurama-alpaca
    filetype: huggingfacehub
    processor: machine_only
    text_field: output # Specify relevant column names for processing

  # Reference a Hugging Face Hub dataset with its identifier
  - filepath: yaful/DeepfakeTextDetect
    filetype: huggingfacehub
    train_split: test_ood_gpt # Use different splits as train/test
    test_split: test_ood_gpt_para
    human_label: "1" # Specify labels corresponding human/machine text

  # Load multiple files as one dataset by specifying the directory
  - filepath: datasets/test_small_dir
    processor: test_small_dir # Custom "processing" function for parsing
    new_parameter: value # New parameters can be added on the fly

# If you don't specify a parameter, it will keep its default value (defined in lib/default_config.yaml).
methods:
  global:
    base_model_name: gpt2-medium
    mask_filling_model_name: t5-large
    DEVICE: cuda
    cache_dir: .cache
  list:
  - name: MiracleMetric
  - name: MiracleMetric
    new_parameter: value # New parameters can be added on the flynew_parameter: value # New parameters can be added on the fly
  - name: LoglikelihoodMetric
  - name: LogRankMetric
  - name: EntropyMetric
  - name: DetectLLM_LLR
  - name: MFDMetric
    clf_algo_for_threshold:
      name: MLPClassifier
      hidden_layer_sizes: [64, 32, 16]
  - name: DetectGPT
  - name: DetectLLM_NPR
  - name: DetectLLM_NPR
    int8: True
    pct_words_masked: 0.4
    span_length: 3
    n_perturbation_rounds: 2
    n_perturbations: 5
  # Methods can be available locally or from Hugging Face
  - name: roberta-base-openai-detector
  - name: Hello-SimpleAI/chatgpt-detector-roberta
# You can either list different analysis methods by name
# Or select " - name: all" to run all available  
analysis:
  - name: all
  
...
